[package]
name = "kneed_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
ndarray = "0"
ndarray-linalg = { version = "0", features = ["openblas-system"] }
ndarray-stats = "0"
ndarray-interp = "0"
rand = "0"
rand_distr = "0"
polyfit-rs = "0"

[dev-dependencies]
approx = "0.4.0"
